Support for exporting to GCloud Functions / Firebase Functions
phero-hq/phero pull request #76
Opened 2022-10-27 15:11 UTC by kamilafsar

Before this change you could only create an export for NodeJS. This PR makes makes the export compatible with GCloud Functions / Firebase Functions. Because we now have 2 "flavors" for the export, we added a new flag "--flavor" to the export command. 

To create a NodeJS compatible export:
```
npx phero server export --flavor nodejs
```

To create a GCloud Functions / Firebase Functions compatible export:
```
npx phero server export --flavor gcloud-functions
```

These will output an "export" directory in your project directory. In it, you will find a directory for each service you've defined in your `phero.ts` file.

To run the NodeJS exported services:

```
node ./export/helloWorldService/index.js
```

To deploy a services to Firebase/GCloud, you should run:

```
gcloud functions deploy helloWorldService 
    --trigger-http 
    --runtime nodejs16 
    --entry-point helloWorldService 
    --source "./export/helloWorldService"
```

For every service we will export a different bundle. We will of course document all this in docs after release.

2022-11-01 10:59 UTC, Jpunt requested changes
Great work, as always 😊

2022-11-04 15:35 UTC, kamilafsar commented on packages/dev/src/cli/commands.ts
> +      console.log(`GOT |${flavor}|`)
Fix in #79

2022-11-04 15:36 UTC, kamilafsar commented on packages/server/src/commands/export/gcloud-functions/generateServiceIndexFile.ts
> +        return requestListener(req, res)
Good catch :) Fix in #79

2022-11-04 15:37 UTC, kamilafsar commented on packages/server/src/commands/export/gcloud-functions/generateLibFile.ts
> +    tsx.verbatim(`export function parseServiceAndFunction(url: string) {
The difference is that this is just "static" code we ship with the export. The other stuff is generated dynamically. 
I intend to fix this in the upcoming refactor. For now, this is the way we do it.

2022-11-04 15:38 UTC, kamilafsar commented on packages/dev/src/cli/commands.ts
> +  flavor: string
I made it a string because I thought it would be better to parse/validate it, and then convert it to the enum. 
Is there a better way to do this?

2022-11-04 15:38 UTC, kamilafsar commented on packages/dev/src/cli/commands.ts
> +  flavor: string
A right. Thanks, will add the help text to #79

2022-11-04 16:09 UTC, Jpunt approved these changes
💪

2022-11-04 16:09 UTC, merged